name: bayes_cut3r
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.4.*
  - torchvision
  - torchaudio
  - pytorch-cuda=12.4
  - numpy=1.26.4
  - pillow=10.3.0
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - h5py
  - pip
  - pip:
      - --extra-index-url https://docs.gsplat.studio/whl/pt24cu124
      - gsplat
      - ninja
      - jaxtyping
      - rich
      - roma
      - gradio
      - einops
      - trimesh
      - tensorboard
      - pyglet<2
      - huggingface-hub[torch]>=0.22
      - viser
      - lpips
      - hydra-core
      - accelerate
      - transformers
      - opencv-python
